// constants/propertyData.js - Comprehensive Property Data for Pune Dream Homes

import images from "../assets/images/images";

/**
 * Helper to flatten image arrays from the images object
 */
const flattenImages = (imgList) => {
  return imgList.flatMap((img) => (Array.isArray(img) ? img : [img]));
};

/**
 * Filter Options
 */
export const bhkOptions = [
  { value: "all", label: "All BHK" },
  { value: "1", label: "1 BHK" },
  { value: "2", label: "2 BHK" },
  { value: "3", label: "3 BHK" },
  { value: "4", label: "4 BHK" },
  { value: "5", label: "5 BHK" },
  { value: "6+", label: "6+ BHK" },
];

export const budgetOptions = [
  { value: "all", label: "All Budgets" },
  { value: "0-5000000", label: "Under ₹ 50 Lac" },
  { value: "5000000-10000000", label: "₹ 50 Lac - ₹ 1 Cr" },
  { value: "10000000-15000000", label: "₹ 1 Cr - ₹ 1.5 Cr" },
  { value: "15000000-999999999", label: "Above ₹ 1.5 Cr" },
];

export const furnishingOptions = [
  { value: "all", label: "All Types" },
  { value: "Furnished", label: "Furnished" },
  { value: "Semi-Furnished", label: "Semi-Furnished" },
  { value: "Unfurnished", label: "Unfurnished" },
];

/**
 * Grouped Property Type Options
 */
export const propertyTypeOptions = [
  {
    label: "Residential Properties",
    options: [
      { value: "1 RK / Studio Apartment", label: "1 RK / Studio Apartment" },
      { value: "1 BHK Apartment", label: "1 BHK Apartment" },
      { value: "2 BHK Apartment", label: "2 BHK Apartment" },
      { value: "3 BHK Apartment", label: "3 BHK Apartment" },
      { value: "4 BHK / 5 BHK Apartment", label: "4+ BHK Apartment" },
      { value: "Residential Flat", label: "Residential Flat" },
      { value: "Builder Floor", label: "Builder Floor" },
      { value: "Duplex Apartment", label: "Duplex Apartment" },
      { value: "Penthouse", label: "Penthouse" },
      { value: "Row House", label: "Row House" },
      { value: "Villa", label: "Villa" },
      { value: "Bungalow", label: "Bungalow" },
      { value: "Independent House", label: "Independent House" },
      { value: "Farm House", label: "Farm House" },
      { value: "Weekend Home", label: "Weekend Home" },
      { value: "Luxury Home", label: "Luxury Home" },
    ],
  },
  {
    label: "Commercial Properties",
    options: [
      { value: "Commercial Office Space", label: "Office Space" },
      { value: "IT / Tech Park Office", label: "IT Park Office" },
      { value: "Co-working Space", label: "Co-working Space" },
      { value: "Business Center", label: "Business Center" },
      { value: "Corporate Office", label: "Corporate Office" },
      { value: "Commercial Building", label: "Commercial Building" },
      { value: "Shop", label: "Shop" },
      { value: "Showroom", label: "Showroom" },
      { value: "Retail Space", label: "Retail Space" },
      { value: "Mall Shop", label: "Mall Shop" },
    ],
  },
  {
    label: "Industrial Properties",
    options: [
      { value: "Industrial Plot", label: "Industrial Plot" },
      { value: "Factory", label: "Factory" },
      { value: "Manufacturing Unit", label: "Manufacturing Unit" },
      { value: "Warehouse", label: "Warehouse" },
      { value: "Godown", label: "Godown" },
      { value: "Logistics Park", label: "Logistics Park" },
    ],
  },
  {
    label: "Land / Plot Properties",
    options: [
      { value: "Residential Plot", label: "Residential Plot" },
      { value: "Commercial Plot", label: "Commercial Plot" },
      { value: "NA Plot", label: "NA Plot" },
      { value: "Agricultural Land", label: "Agricultural Land" },
      { value: "Farm Land", label: "Farm Land" },
      { value: "Gated Community Plot", label: "Gated Community Plot" },
      { value: "Township Plot", label: "Township Plot" },
    ],
  },
];

/**
 * Popular Choices Categories (For Home Page/Quick Access)
 */
export const popularChoices = [
  {
    id: "rtm",
    title: "Ready to Move",
    image: images.img_3[0],
    count: "12,500+",
    link: "/buy/ready-to-move",
  },
  {
    id: "owner",
    title: "Owner Properties",
    image: images.img_4[0],
    count: "5,200+",
    link: "/buy/owner-properties",
  },
  {
    id: "budget",
    title: "Budget Homes",
    image: images.img_5[0],
    count: "8,100+",
    link: "/buy/budget-homes",
  },
  {
    id: "premium",
    title: "Premium Homes",
    image: images.img_6[0],
    count: "3,400+",
    link: "/buy/premium-homes",
  },
  {
    id: "new",
    title: "New Projects",
    image: images.img_7[0],
    count: "450+",
    link: "/buy/new-projects",
  },
];

/**
 * Property Types with Icons
 */
export const propertyTypes = [
  {
    id: "flats",
    title: "Flats in Pune",
    icon: "Building2",
    count: "18,200+",
    link: "/buy/flats-pune",
  },
  {
    id: "house",
    title: "House for sale",
    icon: "Home",
    count: "2,500+",
    link: "/buy/house-pune",
  },
  {
    id: "villa",
    title: "Villa in Pune",
    icon: "Landmark",
    count: "1,200+",
    link: "/buy/villa-pune",
  },
  {
    id: "plot",
    title: "Plot in Pune",
    icon: "Map",
    count: "3,800+",
    link: "/buy/plot-pune",
  },
  {
    id: "office",
    title: "Office Space",
    icon: "Briefcase",
    count: "1,500+",
    link: "/buy/office-pune",
  },
  {
    id: "commercial",
    title: "Commercial Space",
    icon: "Store",
    count: "2,100+",
    link: "/buy/commercial-pune",
  },
];

/**
 * 44 Detailed Properties for Pune
 */
export const properties = [
  {
    id: 1,
    title: "Sunit Laxmi Sharda",
    location: "Ghole Road",
    area: "Pune",
    bhk: 4,
    carpetArea: 1500,
    price: 33500000,
    pricePerSqft: 16750,
    floor: "4 out of 5",
    bathrooms: 4,
    balconies: 2,
    parking: "1 Covered",
    furnishing: "Unfurnished",
    facing: "North - East",
    ownership: "Co-operative Society",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "4 BHK / 5 BHK Apartment",
    amenities: [
      "Power Backup",
      "Reserved Parking",
      "Security",
      "Air Conditioned",
      "Intercom",
    ],
    images: flattenImages([
      images.img_3,
      images.img_4,
      images.img_5,
      images.img_6,
    ]),
    postedTime: "10 hours ago",
    agentName: "Vijay",
    agentType: "Agent",
    description:
      "This spacious 4 BHK apartment can be found for sale in Ghole Road, Pune. Fully laminated with all modern amenities.",
  },
  {
    id: 2,
    title: "Sahakar Nagar",
    location: "Parvati Paytha",
    area: "Pune",
    bhk: 2,
    carpetArea: 830,
    price: 15500000,
    pricePerSqft: 14091,
    floor: "5 out of 12",
    bathrooms: 2,
    balconies: 2,
    parking: "1 Covered",
    furnishing: "Semi-Furnished",
    facing: "East",
    status: "Ready to Move",
    transaction: "New Property",
    propertyType: "2 BHK Apartment",
    amenities: [
      "Power Backup",
      "Reserved Parking",
      "Security",
      "Visitor Parking",
    ],
    images: flattenImages([
      images.img_4,
      images.img_5,
      images.img_6,
      images.img_7,
    ]),
    postedTime: "10 hours ago",
    agentName: "Siddhivinayak Estate and Developers",
    agentType: "Agent",
    description:
      "East Facing Property. All amenities big nice society very prime area semi furnished flat hurry up.",
  },
  {
    id: 3,
    title: "Iris Society",
    location: "Balewadi",
    area: "Pune",
    bhk: 2,
    carpetArea: 1050,
    price: 15000000,
    pricePerSqft: 9740,
    floor: "5 out of 9",
    bathrooms: 2,
    balconies: 2,
    parking: "1 Covered",
    furnishing: "Semi-Furnished",
    facing: "West",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "2 BHK Apartment",
    amenities: [
      "Power Backup",
      "Reserved Parking",
      "Security",
      "Service/Goods Lift",
      "Air Conditioned",
      "Visitor Parking",
      "RO Water System",
    ],
    images: flattenImages([
      images.img_5,
      images.img_6,
      images.img_7,
      images.img_8,
    ]),
    postedTime: "2 hours ago",
    agentName: "Smart Home Reality",
    agentType: "Agent",
    description:
      "2BHK Semi Furnished Flat Available For Sale, Middle Floor, 1050 sqft carpet area, visit any time possible.",
  },
  {
    id: 4,
    title: "Fortune Perfect",
    location: "Kondhwa BK",
    area: "Pune",
    bhk: 1,
    carpetArea: 500,
    price: 4200000,
    pricePerSqft: 8400,
    floor: "11 out of 12",
    bathrooms: 1,
    balconies: 2,
    parking: "1 Covered",
    furnishing: "Semi-Furnished",
    facing: "North",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "1 BHK Apartment",
    amenities: [
      "Power Backup",
      "Reserved Parking",
      "Security",
      "Intercom Facility",
    ],
    images: flattenImages([
      images.img_6,
      images.img_7,
      images.img_8,
      images.img_9,
    ]),
    postedTime: "10 hours ago",
    agentName: "ShaSha",
    agentType: "Owner",
    description:
      "This well maintained 1 BHK residence is currently offered for sale in Kondhwa Budruk, Pune.",
  },
  {
    id: 5,
    title: "Unique K Shire",
    location: "Punawale",
    area: "Pimpri Chinchwad",
    bhk: 3,
    carpetArea: 1012,
    price: 11900000,
    pricePerSqft: 8500,
    floor: "11 out of 20",
    bathrooms: 3,
    balconies: 2,
    parking: "1 Covered",
    furnishing: "Unfurnished",
    facing: "East",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "3 BHK Apartment",
    amenities: [
      "Power Backup",
      "Reserved Parking",
      "Security",
      "Service/Goods Lift",
    ],
    images: flattenImages([
      images.img_7,
      images.img_8,
      images.img_9,
      images.img_10,
    ]),
    postedTime: "1 hour ago",
    agentName: "Bhushan",
    agentType: "Owner",
    description:
      "Spacious 3BHK flat in prime location with all modern amenities.",
  },
  {
    id: 6,
    title: "K Raheja Vistas Premiere Magna",
    location: "Kondhwa",
    area: "Pune",
    bhk: 3,
    carpetArea: 1400,
    price: 34500000,
    pricePerSqft: 11500,
    floor: "2 out of 18",
    bathrooms: 4,
    balconies: 3,
    parking: "2 Covered",
    furnishing: "Semi-Furnished",
    facing: "South",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "3 BHK Apartment",
    amenities: [
      "Power Backup",
      "Reserved Parking",
      "Security",
      "Visitor Parking",
      "Intercom Facility",
      "RO Water System",
    ],
    images: flattenImages([
      images.img_8,
      images.img_9,
      images.img_10,
      images.img_11,
    ]),
    postedTime: "Dec 27, '25",
    agentName: "Twin Realty",
    agentType: "Agent",
    description:
      "An Elegant 3 BHK flat located in Kondhwa, Pune is now available for sale.",
  },
  {
    id: 7,
    title: "Naiknavare Neelaya",
    location: "Talegaon Dabhade",
    area: "Pune",
    bhk: 2,
    carpetArea: 578,
    price: 4700000,
    pricePerSqft: 6018,
    floor: "11 out of 12",
    bathrooms: 2,
    balconies: 2,
    parking: "1 Covered",
    furnishing: "Semi-Furnished",
    facing: "West",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "2 BHK Apartment",
    amenities: [
      "Power Backup",
      "Reserved Parking",
      "Security",
      "Visitor Parking",
    ],
    images: flattenImages([
      images.img_9,
      images.img_10,
      images.img_11,
      images.img_12,
    ]),
    postedTime: "11 hours ago",
    agentName: "Prathmesh",
    agentType: "Owner",
    description:
      "Explore this 2 BHK apartment in Talegaon Dabhade to buy or invest in Pune city.",
  },
  {
    id: 8,
    title: "Kamakshie Suhas Sudhanva",
    location: "Rambaug Colony, Kothrud",
    area: "Pune",
    bhk: 2,
    carpetArea: 800,
    price: 13500000,
    pricePerSqft: 12857,
    floor: "6 out of 16",
    bathrooms: 2,
    balconies: 1,
    parking: "1 Covered",
    furnishing: "Unfurnished",
    facing: "East",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "2 BHK Apartment",
    amenities: ["Reserved Parking"],
    images: flattenImages([
      images.img_10,
      images.img_11,
      images.img_12,
      images.img_13,
    ]),
    postedTime: "Dec 27, '25",
    agentName: "Abhang Estates",
    agentType: "Agent",
    description:
      "East Facing Property. Come home to Kamakshie Rambaug Colony, Pune has an attractive 2 BHK apartment for sale.",
  },
  {
    id: 9,
    title: "Tain Square",
    location: "Fatima Nagar Wanowrie",
    area: "Pune",
    bhk: 3,
    carpetArea: 1250,
    price: 13500000,
    pricePerSqft: 8182,
    floor: "5 out of 11",
    bathrooms: 3,
    balconies: 2,
    parking: "2 Covered",
    furnishing: "Unfurnished",
    facing: "East",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "3 BHK Apartment",
    amenities: [
      "Power Backup",
      "Reserved Parking",
      "Security",
      "Service/Goods Lift",
      "Visitor Parking",
    ],
    images: flattenImages([
      images.img_11,
      images.img_12,
      images.img_13,
      images.img_14,
    ]),
    postedTime: "Dec 27, '25",
    agentName: "N & G Enterprises",
    agentType: "Agent",
    description:
      "East Facing Property. Near Inamdar hospital. A well-positioned 3 BHK flat in Fatima Nagar.",
  },
  {
    id: 10,
    title: "Shubh Shagun",
    location: "Kharadi",
    area: "Pune",
    bhk: 2,
    carpetArea: 839,
    price: 9000000,
    pricePerSqft: 10727,
    floor: "6 out of 14",
    bathrooms: 2,
    balconies: 2,
    parking: "1 Covered",
    furnishing: "Unfurnished",
    facing: "East",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "Residential Flat",
    amenities: ["Reserved Parking", "Security"],
    images: flattenImages([
      images.img_12,
      images.img_13,
      images.img_14,
      images.img_15,
    ]),
    postedTime: "Dec 27, '25",
    agentName: "Property Dot Com",
    agentType: "Agent",
    description:
      "The 2 BHK apartment is immediately available for sale in Kharadi.",
  },
  {
    id: 11,
    title: "Green Valley Farmhouse",
    location: "Mulshi",
    area: "Pune",
    bhk: 4,
    carpetArea: 3500,
    price: 45000000,
    pricePerSqft: 9000,
    floor: "Ground",
    bathrooms: 5,
    balconies: 4,
    parking: "4 Open",
    furnishing: "Furnished",
    facing: "North",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "Farm House",
    amenities: ["Private Garden", "Pool", "Power Backup"],
    images: flattenImages([images.img_3, images.img_4, images.img_5]),
    postedTime: "5 days ago",
    agentName: "Nature Homes",
    agentType: "Agent",
    description: "Beautiful 4BHK Farmhouse in the lap of nature.",
  },
  {
    id: 12,
    title: "Phoenix Market City Shop",
    location: "Viman Nagar",
    area: "Pune",
    bhk: 0,
    carpetArea: 800,
    price: 35000000,
    pricePerSqft: 29166,
    floor: "2",
    bathrooms: 1,
    balconies: 0,
    parking: "Public",
    furnishing: "Unfurnished",
    facing: "North-East",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "Shop",
    amenities: ["Central AC", "Fire Safety", "CCTV"],
    images: flattenImages([images.img_6, images.img_7]),
    postedTime: "1 week ago",
    agentName: "Commercial Experts",
    agentType: "Agent",
    description: "Prime retail shop available in Phoenix Market City.",
  },
  {
    id: 13,
    title: "IT Park Office Space",
    location: "Hinjewadi Phase 1",
    area: "Pune",
    bhk: 0,
    carpetArea: 2500,
    price: 28000000,
    pricePerSqft: 8000,
    floor: "5",
    bathrooms: 2,
    balconies: 1,
    parking: "3 Covered",
    furnishing: "Furnished",
    facing: "East",
    status: "Ready to Move",
    transaction: "New Property",
    propertyType: "IT / Tech Park Office",
    amenities: ["Conference Room", "Cafeteria", "High Speed Internet"],
    images: flattenImages([images.img_8, images.img_9]),
    postedTime: "3 days ago",
    agentName: "Tech Realty",
    agentType: "Agent",
    description: "Fully furnished office space in prime IT hub.",
  },
  {
    id: 14,
    title: "Industrial Plot MIDC",
    location: "Chakan",
    area: "Pune",
    bhk: 0,
    carpetArea: 5000,
    price: 15000000,
    pricePerSqft: 3000,
    floor: "G",
    bathrooms: 0,
    balconies: 0,
    parking: "Open",
    furnishing: "Unfurnished",
    facing: "North",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "Industrial Plot",
    amenities: ["Water Connection", "Electricity"],
    images: flattenImages([images.img_10]),
    postedTime: "2 weeks ago",
    agentName: "Industrial Hub",
    agentType: "Agent",
    description: "5000 sqft industrial plot available in Chakan MIDC.",
  },
  {
    id: 15,
    title: "Luxury Villa Project",
    location: "Wagholi",
    area: "Pune",
    bhk: 4,
    carpetArea: 2800,
    price: 25000000,
    pricePerSqft: 6250,
    floor: "G+1",
    bathrooms: 4,
    balconies: 3,
    parking: "2 Covered",
    furnishing: "Unfurnished",
    facing: "East",
    status: "New Launch",
    transaction: "New Property",
    propertyType: "Villa",
    amenities: ["Clubhouse", "Swimming Pool", "Gym"],
    images: flattenImages([images.img_11, images.img_12]),
    postedTime: "Just now",
    agentName: "Dream Homes Builders",
    agentType: "Builder",
    description: "Exquisite 4 BHK luxury villas in a gated community.",
  },
  {
    id: 16,
    title: "Small Office Space",
    location: "Kothrud",
    area: "Pune",
    bhk: 0,
    carpetArea: 300,
    price: 4500000,
    pricePerSqft: 10000,
    floor: "2",
    bathrooms: 1,
    balconies: 0,
    parking: "Common",
    furnishing: "Semi-Furnished",
    facing: "East",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "Commercial Office Space",
    amenities: ["Lift", "Security"],
    images: flattenImages([images.img_4, images.img_5]),
    postedTime: "2 days ago",
    agentName: "Surendra",
    agentType: "Owner",
    description:
      "Ideal small office for startups or professionals in prime Kothrud area.",
  },
  {
    id: 17,
    title: "Residential Plot",
    location: "Wagholi",
    area: "Pune",
    bhk: 0,
    carpetArea: 1500,
    price: 3500000,
    pricePerSqft: 2333,
    floor: "G",
    bathrooms: 0,
    balconies: 0,
    parking: "Open",
    furnishing: "Unfurnished",
    facing: "North",
    status: "New Launch",
    transaction: "New Property",
    propertyType: "Residential Plot",
    amenities: ["Water Connection", "Boundary Wall"],
    images: flattenImages([images.img_6]),
    postedTime: "1 day ago",
    agentName: "Land Developers",
    agentType: "Agent",
    description: "NA sanctioned residential plot in developing area.",
  },
  {
    id: 18,
    title: "Highway Warehouse",
    location: "Chakan",
    area: "Pune",
    bhk: 0,
    carpetArea: 2000,
    price: 7500000,
    pricePerSqft: 3750,
    floor: "G",
    bathrooms: 1,
    balconies: 0,
    parking: "Truck Bay",
    furnishing: "Unfurnished",
    facing: "West",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "Warehouse",
    amenities: ["Loading Dock", "High Ceiling", "Security"],
    images: flattenImages([images.img_7]),
    postedTime: "4 days ago",
    agentName: "Logistics Infra",
    agentType: "Agent",
    description: "Ready warehouse on main highway with excellent connectivity.",
  },
  {
    id: 19,
    title: "Premium Showroom",
    location: "Baner",
    area: "Pune",
    bhk: 0,
    carpetArea: 1200,
    price: 48000000,
    pricePerSqft: 26666,
    floor: "G",
    bathrooms: 2,
    balconies: 0,
    parking: "Valet",
    furnishing: "Unfurnished",
    facing: "Main Road",
    status: "Ready to Move",
    transaction: "New Property",
    propertyType: "Showroom",
    amenities: ["Glass Facade", "Central AC", "Parking"],
    images: flattenImages([images.img_8, images.img_9]),
    postedTime: "Just now",
    agentName: "Prime Commercials",
    agentType: "Agent",
    description: "High visibility showroom on Baner main road.",
  },
  {
    id: 20,
    title: "Weekend Villa",
    location: "Lonavala",
    area: "Pune Outskirts",
    bhk: 3,
    carpetArea: 2000,
    price: 22000000,
    pricePerSqft: 7333,
    floor: "G+1",
    bathrooms: 3,
    balconies: 2,
    parking: "2 Covered",
    furnishing: "Furnished",
    facing: "East",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "Weekend Home",
    amenities: ["Private Pool", "Garden", "Caretaker"],
    images: flattenImages([images.img_10, images.img_11, images.img_12]),
    postedTime: "1 week ago",
    agentName: "Rahul",
    agentType: "Owner",
    description: "Fully furnished weekend getaway villa.",
  },
  {
    id: 21,
    title: "Compact Studio",
    location: "Viman Nagar",
    area: "Pune",
    bhk: 1,
    carpetArea: 350,
    price: 3200000,
    pricePerSqft: 6400,
    floor: "3",
    bathrooms: 1,
    balconies: 1,
    parking: "1 Bike",
    furnishing: "Furnished",
    facing: "North",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "1 RK / Studio Apartment",
    amenities: ["Lift", "Security"],
    images: flattenImages([images.img_3]),
    postedTime: "1 day ago",
    agentName: "Quick Homes",
    agentType: "Agent",
    description: "Cozy furnished studio apartment near airport.",
  },
  {
    id: 22,
    title: "Independent Builder Floor",
    location: "Sahakar Nagar",
    area: "Pune",
    bhk: 3,
    carpetArea: 1100,
    price: 16500000,
    pricePerSqft: 11785,
    floor: "2",
    bathrooms: 3,
    balconies: 2,
    parking: "1 Covered",
    furnishing: "Unfurnished",
    facing: "East",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "Builder Floor",
    amenities: ["Private Terrace", "Water Storage"],
    images: flattenImages([images.img_4]),
    postedTime: "2 days ago",
    agentName: "Local realty",
    agentType: "Agent",
    description: "Spacious independent floor in quiet locality.",
  },
  {
    id: 23,
    title: "Luxury Penthouse",
    location: "Kalyani Nagar",
    area: "Pune",
    bhk: 4,
    carpetArea: 3000,
    price: 65000000,
    pricePerSqft: 14444,
    floor: "12",
    bathrooms: 5,
    balconies: 4,
    parking: "3 Covered",
    furnishing: "Furnished",
    facing: "East",
    status: "Ready to Move",
    transaction: "New Property",
    propertyType: "Penthouse",
    amenities: ["Private Pool", "Terrace Garden", "Jacuzzi"],
    images: flattenImages([images.img_5, images.img_6]),
    postedTime: "Just now",
    agentName: "Elite Homes",
    agentType: "Agent",
    description: "Ultra luxury penthouse with panoramic river view.",
  },
  {
    id: 24,
    title: "Corner Row House",
    location: "Magarpatta",
    area: "Pune",
    bhk: 3,
    carpetArea: 1800,
    price: 21000000,
    pricePerSqft: 9545,
    floor: "G+1",
    bathrooms: 3,
    balconies: 2,
    parking: "1 Covered",
    furnishing: "Semi-Furnished",
    facing: "West",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "Row House",
    amenities: ["Backyard", "Security", "Clubhouse"],
    images: flattenImages([images.img_7]),
    postedTime: "3 days ago",
    agentName: "City Properties",
    agentType: "Agent",
    description: "Well maintained row house in township.",
  },
  {
    id: 25,
    title: "Vintage Bungalow",
    location: "Prabhat Road",
    area: "Pune",
    bhk: 5,
    carpetArea: 4000,
    price: 85000000,
    pricePerSqft: 17000,
    floor: "G+1",
    bathrooms: 5,
    balconies: 3,
    parking: "3 Open",
    furnishing: "Unfurnished",
    facing: "North",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "Bungalow",
    amenities: ["Private Garden", "Servant Quarters"],
    images: flattenImages([images.img_8]),
    postedTime: "1 week ago",
    agentName: "Heritage Homes",
    agentType: "Agent",
    description: "Classic bungalow in prestigious Prabhat Road area.",
  },
  {
    id: 26,
    title: "Independent House",
    location: "Kondhwa",
    area: "Pune",
    bhk: 2,
    carpetArea: 900,
    price: 8500000,
    pricePerSqft: 7083,
    floor: "G+1",
    bathrooms: 2,
    balconies: 1,
    parking: "1 Open",
    furnishing: "Unfurnished",
    facing: "South",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "Independent House",
    amenities: ["Water Storage"],
    images: flattenImages([images.img_9]),
    postedTime: "4 days ago",
    agentName: "Owner",
    agentType: "Owner",
    description: "Affordable independent house for small family.",
  },
  {
    id: 27,
    title: "Co-working Desk",
    location: "Baner",
    area: "Pune",
    bhk: 0,
    carpetArea: 50,
    price: 5000,
    pricePerSqft: 50,
    floor: "3",
    bathrooms: 1,
    balconies: 0,
    parking: "Common",
    furnishing: "Furnished",
    facing: "North",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "Co-working Space",
    amenities: ["WiFi", "AC", "Coffee"],
    images: flattenImages([images.img_10]),
    postedTime: "Today",
    agentName: "WorkHub",
    agentType: "Agent",
    description: "Single desk in premium co-working space.",
  },
  {
    id: 28,
    title: "Business Center Office",
    location: "Shivajinagar",
    area: "Pune",
    bhk: 0,
    carpetArea: 500,
    price: 15000000,
    pricePerSqft: 18750,
    floor: "4",
    bathrooms: 1,
    balconies: 0,
    parking: "Valet",
    furnishing: "Furnished",
    facing: "East",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "Business Center",
    amenities: ["Reception", "Meeting Rooms"],
    images: flattenImages([images.img_11]),
    postedTime: "2 days ago",
    agentName: "Biz Space",
    agentType: "Agent",
    description: "Premium office in established business center.",
  },
  {
    id: 29,
    title: "Corporate House",
    location: "Hinjewadi",
    area: "Pune",
    bhk: 0,
    carpetArea: 10000,
    price: 120000000,
    pricePerSqft: 8000,
    floor: "G+4",
    bathrooms: 10,
    balconies: 5,
    parking: "20 Covered",
    furnishing: "Unfurnished",
    facing: "North",
    status: "Ready to Move",
    transaction: "New Property",
    propertyType: "Corporate Office",
    amenities: ["Central AC", "Cafeteria", "Auditorium"],
    images: flattenImages([images.img_12]),
    postedTime: "1 week ago",
    agentName: "Global Realty",
    agentType: "Agent",
    description: "Standalone corporate building for large MNC.",
  },
  {
    id: 30,
    title: "Commercial Building",
    location: "Deccan",
    area: "Pune",
    bhk: 0,
    carpetArea: 5000,
    price: 80000000,
    pricePerSqft: 10000,
    floor: "G+3",
    bathrooms: 4,
    balconies: 2,
    parking: "10 Open",
    furnishing: "Semi-Furnished",
    facing: "Main Road",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "Commercial Building",
    amenities: ["Lift", "Power Backup"],
    images: flattenImages([images.img_3]),
    postedTime: "3 days ago",
    agentName: "City Commercials",
    agentType: "Agent",
    description: "Prime commercial building on FC Road.",
  },
  {
    id: 31,
    title: "High Street Retail",
    location: "Aundh",
    area: "Pune",
    bhk: 0,
    carpetArea: 800,
    price: 25000000,
    pricePerSqft: 25000,
    floor: "G",
    bathrooms: 1,
    balconies: 0,
    parking: "Public",
    furnishing: "Unfurnished",
    facing: "West",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "Retail Space",
    amenities: ["Glass Frontage"],
    images: flattenImages([images.img_4]),
    postedTime: "1 day ago",
    agentName: "Shop Finders",
    agentType: "Agent",
    description: "Retail space in busy Aundh market.",
  },
  {
    id: 32,
    title: "Mall Shop",
    location: "Hadapsar",
    area: "Pune",
    bhk: 0,
    carpetArea: 400,
    price: 12000000,
    pricePerSqft: 20000,
    floor: "1",
    bathrooms: 1,
    balconies: 0,
    parking: "Mall Parking",
    furnishing: "Unfurnished",
    facing: "East",
    status: "Ready to Move",
    transaction: "New Property",
    propertyType: "Mall Shop",
    amenities: ["Central AC", "Fire Safety"],
    images: flattenImages([images.img_5]),
    postedTime: "2 days ago",
    agentName: "Mall Mangement",
    agentType: "Builder",
    description: "Shop available in Seasons Mall.",
  },
  {
    id: 33,
    title: "Manufacturing Factory",
    location: "Bhosari MIDC",
    area: "Pune",
    bhk: 0,
    carpetArea: 8000,
    price: 35000000,
    pricePerSqft: 3500,
    floor: "G",
    bathrooms: 4,
    balconies: 0,
    parking: "Truck Parking",
    furnishing: "Unfurnished",
    facing: "North",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "Factory",
    amenities: ["Industrial Power", "Water Plant"],
    images: flattenImages([images.img_6]),
    postedTime: "1 week ago",
    agentName: "MIDC Agents",
    agentType: "Agent",
    description: "Fully functional factory shed in Bhosari.",
  },
  {
    id: 34,
    title: "Small Mfg Unit",
    location: "Pimpri",
    area: "Pune",
    bhk: 0,
    carpetArea: 2000,
    price: 9000000,
    pricePerSqft: 3600,
    floor: "G",
    bathrooms: 1,
    balconies: 0,
    parking: "Open",
    furnishing: "Unfurnished",
    facing: "East",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "Manufacturing Unit",
    amenities: ["Three Phase Power"],
    images: flattenImages([images.img_7]),
    postedTime: "3 days ago",
    agentName: "SME Properties",
    agentType: "Owner",
    description: "Small manufacturing unit suitable for engineering works.",
  },
  {
    id: 35,
    title: "Storage Godown",
    location: "Phursungi",
    area: "Pune",
    bhk: 0,
    carpetArea: 3000,
    price: 8000000,
    pricePerSqft: 2285,
    floor: "G",
    bathrooms: 0,
    balconies: 0,
    parking: "Truck Access",
    furnishing: "Unfurnished",
    facing: "West",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "Godown",
    amenities: ["Security", "Wide Gate"],
    images: flattenImages([images.img_8]),
    postedTime: "4 days ago",
    agentName: "Warehouse Walas",
    agentType: "Agent",
    description: "Dry storage godown near highway.",
  },
  {
    id: 36,
    title: "Logistics Park Space",
    location: "Talegaon",
    area: "Pune",
    bhk: 0,
    carpetArea: 15000,
    price: 60000000,
    pricePerSqft: 3000,
    floor: "G",
    bathrooms: 4,
    balconies: 0,
    parking: "Ample",
    furnishing: "Unfurnished",
    facing: "North",
    status: "Ready to Move",
    transaction: "New Property",
    propertyType: "Logistics Park",
    amenities: ["Loading Bays", "Fire Fighting"],
    images: flattenImages([images.img_9]),
    postedTime: "2 weeks ago",
    agentName: "Logistics Experts",
    agentType: "Agent",
    description: "Grade A warehousing space in logistics park.",
  },
  {
    id: 37,
    title: "Commercial Plot",
    location: "Hinjewadi Phase 2",
    area: "Pune",
    bhk: 0,
    carpetArea: 10000,
    price: 40000000,
    pricePerSqft: 4000,
    floor: "G",
    bathrooms: 0,
    balconies: 0,
    parking: "Open",
    furnishing: "Unfurnished",
    facing: "Main Road",
    status: "New Launch",
    transaction: "Resale",
    propertyType: "Commercial Plot",
    amenities: ["Compound Wall"],
    images: flattenImages([images.img_10]),
    postedTime: "1 month ago",
    agentName: "Land Bank",
    agentType: "Agent",
    description: "Prime commercial plot suitable for hotel or office.",
  },
  {
    id: 38,
    title: "NA Plot",
    location: "Pirangut",
    area: "Pune",
    bhk: 0,
    carpetArea: 2000,
    price: 3000000,
    pricePerSqft: 1500,
    floor: "G",
    bathrooms: 0,
    balconies: 0,
    parking: "Open",
    furnishing: "Unfurnished",
    facing: "East",
    status: "New Launch",
    transaction: "New Property",
    propertyType: "NA Plot",
    amenities: ["Water", "Electricity"],
    images: flattenImages([images.img_11]),
    postedTime: "2 days ago",
    agentName: "Plot Sellers",
    agentType: "Agent",
    description: "Sanctioned NA plot with clear title.",
  },
  {
    id: 39,
    title: "Agricultural Land",
    location: "Saswad",
    area: "Pune",
    bhk: 0,
    carpetArea: 43560,
    price: 5000000,
    pricePerSqft: 114,
    floor: "G",
    bathrooms: 0,
    balconies: 0,
    parking: "Open",
    furnishing: "Unfurnished",
    facing: "North",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "Agricultural Land",
    amenities: ["Well Water"],
    images: flattenImages([images.img_12]),
    postedTime: "1 week ago",
    agentName: "Farmer",
    agentType: "Owner",
    description: "1 Acre fertile agricultural land near Saswad.",
  },
  {
    id: 40,
    title: "Farm Land",
    location: "Theur",
    area: "Pune",
    bhk: 0,
    carpetArea: 21780,
    price: 3500000,
    pricePerSqft: 160,
    floor: "G",
    bathrooms: 0,
    balconies: 0,
    parking: "Open",
    furnishing: "Unfurnished",
    facing: "East",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "Farm Land",
    amenities: ["Fencing"],
    images: flattenImages([images.img_3]),
    postedTime: "3 days ago",
    agentName: "Green Earth",
    agentType: "Agent",
    description: "Half acre farm land suitable for organic farming.",
  },
  {
    id: 41,
    title: "Gated Community Plot",
    location: "Mhalunge",
    area: "Pune",
    bhk: 0,
    carpetArea: 1500,
    price: 5500000,
    pricePerSqft: 3666,
    floor: "G",
    bathrooms: 0,
    balconies: 0,
    parking: "Open",
    furnishing: "Unfurnished",
    facing: "West",
    status: "New Launch",
    transaction: "New Property",
    propertyType: "Gated Community Plot",
    amenities: ["Clubhouse", "Security", "Internal Roads"],
    images: flattenImages([images.img_4]),
    postedTime: "Just now",
    agentName: "Township Developers",
    agentType: "Builder",
    description: "Premium plots in a riverside township.",
  },
  {
    id: 42,
    title: "Township Plot",
    location: "Nere",
    area: "Pune",
    bhk: 0,
    carpetArea: 1200,
    price: 2800000,
    pricePerSqft: 2333,
    floor: "G",
    bathrooms: 0,
    balconies: 0,
    parking: "Open",
    furnishing: "Unfurnished",
    facing: "East",
    status: "New Launch",
    transaction: "New Property",
    propertyType: "Township Plot",
    amenities: ["Water Supply", "Street Lights"],
    images: flattenImages([images.img_5]),
    postedTime: "2 days ago",
    agentName: "Life City",
    agentType: "Builder",
    description: "Affordable bungalow plots in integrated township.",
  },
  {
    id: 43,
    title: "Modern Duplex",
    location: "Koregaon Park",
    area: "Pune",
    bhk: 3,
    carpetArea: 2200,
    price: 35000000,
    pricePerSqft: 12500,
    floor: "5",
    bathrooms: 3,
    balconies: 3,
    parking: "2 Covered",
    furnishing: "Furnished",
    facing: "South",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "Duplex Apartment",
    amenities: ["Internal Staircase", "Terrace"],
    images: flattenImages([images.img_3]),
    postedTime: "5 days ago",
    agentName: "Luxury Living",
    agentType: "Agent",
    description: "Stylish duplex apartment in posh locality.",
  },
  {
    id: 44,
    title: "Opulent Luxury Home",
    location: "Sopan Baug",
    area: "Pune",
    bhk: 5,
    carpetArea: 5000,
    price: 150000000,
    pricePerSqft: 21428,
    floor: "3",
    bathrooms: 6,
    balconies: 5,
    parking: "4 Covered",
    furnishing: "Furnished",
    facing: "East",
    status: "Ready to Move",
    transaction: "Resale",
    propertyType: "Luxury Home",
    amenities: ["Private Elevator", "Home Theater", "Smart Home"],
    images: flattenImages([images.img_6]),
    postedTime: "1 week ago",
    agentName: "Millionaire Homes",
    agentType: "Agent",
    description: "Ultra-premium 5 BHK luxury residence.",
  },
];

/**
 * Statistics Data
 */
export const statsData = {
  totalProperties: "30,625+",
  newProjects: "2,211+",
  verified: "100%",
  support: "24/7",
};
