// constants/propertyData.js - All Property Data

import images from "../assets/images/images";

export const properties = [
  {
    id: 1,
    title: "Sunit Laxmi Sharda",
    location: "Ghole Road",
    area: "Pune",
    bhk: 4,
    carpetArea: 1500,
    superArea: null,
    price: 33500000,
    pricePerSqft: 16750,
    floor: "4 out of 5",
    bathrooms: 4,
    balconies: 2,
    parking: "1 Covered",
    furnishing: "Unfurnished",
    facing: "North - East",
    overlooking: "Main Road",
    ownership: "Co-operative Society",
    status: "Ready to Move",
    transaction: "Resale",
    amenities: [
      "Power Backup",
      "Reserved Parking",
      "Security",
      "Air Conditioned",
      "Intercom",
    ],
    images: [images.img_3, images.img_4, images.img_5, images.img_6],
    postedTime: "10 hours ago",
    agentName: "Vijay",
    agentType: "Agent",
    agentServed: "500+",
    description:
      "This spacious 4 BHK apartment can be found for sale in Ghole Road, Pune. Fully laminated with all modern amenities.",
  },
  {
    id: 2,
    title: "Sahakar Nagar",
    location: "Parvati Paytha",
    area: "Pune",
    bhk: 2,
    carpetArea: 830,
    superArea: null,
    price: 15500000,
    pricePerSqft: 14091,
    floor: "5 out of 12",
    bathrooms: 2,
    balconies: 2,
    parking: "1 Covered",
    furnishing: "Semi-Furnished",
    facing: "East",
    overlooking: "Main Road",
    ownership: "Freehold",
    status: "Ready to Move",
    transaction: "New Property",
    amenities: [
      "Power Backup",
      "Reserved Parking",
      "Security",
      "Visitor Parking",
    ],
    images: [images.img_4, images.img_5, images.img_6, images.img_7],
    postedTime: "10 hours ago",
    agentName: "Siddhivinayak Estate and Developers",
    agentType: "Agent",
    agentServed: "3000+",
    description:
      "East Facing Property. All amenities big nice society very prime area semi furnished flat hurry up.",
  },
  {
    id: 3,
    title: "Iris Society",
    location: "Balewadi",
    area: "Pune",
    bhk: 2,
    carpetArea: 1050,
    superArea: null,
    price: 15000000,
    pricePerSqft: 9740,
    floor: "5 out of 9",
    bathrooms: 2,
    balconies: 2,
    parking: "1 Covered",
    furnishing: "Semi-Furnished",
    facing: "West",
    overlooking: "Garden/Park, Main Road",
    ownership: "Co-operative Society",
    status: "Ready to Move",
    transaction: "Resale",
    amenities: [
      "Power Backup",
      "Reserved Parking",
      "Security",
      "Service/Goods Lift",
      "Air Conditioned",
      "Visitor Parking",
      "RO Water System",
    ],
    images: [images.img_5, images.img_6, images.img_7, images.img_8],
    postedTime: "2 hours ago",
    agentName: "Smart Home Reality",
    agentType: "Agent",
    agentServed: "100+",
    description:
      "2BHK Semi Furnished Flat Available For Sale, Middle Floor, 1050 sqft carpet area, visit any time possible.",
  },
  {
    id: 4,
    title: "Fortune Perfect",
    location: "Kondhwa BK",
    area: "Pune",
    bhk: 1,
    carpetArea: 500,
    superArea: null,
    price: 4200000,
    pricePerSqft: 8400,
    floor: "11 out of 12",
    bathrooms: 1,
    balconies: 2,
    parking: "1 Covered",
    furnishing: "Semi-Furnished",
    facing: "North",
    overlooking: "City View",
    ownership: "Co-operative Society",
    status: "Ready to Move",
    transaction: "Resale",
    amenities: [
      "Power Backup",
      "Reserved Parking",
      "Security",
      "Intercom Facility",
    ],
    images: [images.img_6, images.img_7, images.img_8, images.img_9],
    postedTime: "10 hours ago",
    agentName: "ShaSha",
    agentType: "Owner",
    agentServed: null,
    description:
      "This well maintained 1 BHK residence is currently offered for sale in Kondhwa Budruk, Pune.",
  },
  {
    id: 5,
    title: "Unique K Shire",
    location: "Punawale",
    area: "Pimpri Chinchwad",
    bhk: 3,
    carpetArea: 1012,
    superArea: null,
    price: 11900000,
    pricePerSqft: 8500,
    floor: "11 out of 20",
    bathrooms: 3,
    balconies: 2,
    parking: "1 Covered",
    furnishing: "Unfurnished",
    facing: "East",
    overlooking: "Pool, Garden/Park, Main Road",
    ownership: "Freehold",
    status: "Ready to Move",
    transaction: "Resale",
    amenities: [
      "Power Backup",
      "Reserved Parking",
      "Security",
      "Service/Goods Lift",
    ],
    images: [images.img_7, images.img_8, images.img_9, images.img_10],
    postedTime: "1 hour ago",
    agentName: "Bhushan",
    agentType: "Owner",
    agentServed: null,
    description:
      "Spacious 3BHK flat in prime location with all modern amenities.",
  },
  {
    id: 6,
    title: "K Raheja Vistas Premiere Magna",
    location: "Kondhwa",
    area: "Pune",
    bhk: 3,
    carpetArea: null,
    superArea: 3000,
    price: 34500000,
    pricePerSqft: 11500,
    floor: "2 out of 18",
    bathrooms: 4,
    balconies: 3,
    parking: "2 Covered",
    furnishing: "Semi-Furnished",
    facing: "South",
    overlooking: "Garden/Park",
    ownership: "Freehold",
    status: "Ready to Move",
    transaction: "Resale",
    amenities: [
      "Power Backup",
      "Reserved Parking",
      "Security",
      "Visitor Parking",
      "Intercom Facility",
      "RO Water System",
    ],
    images: [images.img_8, images.img_9, images.img_10, images.img_11],
    postedTime: "Dec 27, '25",
    agentName: "Twin Realty",
    agentType: "Agent",
    agentServed: "100+",
    description:
      "An Elegant 3 BHK flat located in Kondhwa, Pune is now available for sale.",
  },
  {
    id: 7,
    title: "Naiknavare Neelaya",
    location: "Talegaon Dabhade",
    area: "Pune",
    bhk: 2,
    carpetArea: 578,
    superArea: null,
    price: 4700000,
    pricePerSqft: 6018,
    floor: "11 out of 12",
    bathrooms: 2,
    balconies: 2,
    parking: "1 Covered",
    furnishing: "Semi-Furnished",
    facing: "West",
    overlooking: "Main Road, Garden/Park",
    ownership: "Co-operative Society",
    status: "Ready to Move",
    transaction: "Resale",
    amenities: [
      "Power Backup",
      "Reserved Parking",
      "Security",
      "Visitor Parking",
    ],
    images: [images.img_9, images.img_10, images.img_11, images.img_12],
    postedTime: "11 hours ago",
    agentName: "Prathmesh",
    agentType: "Owner",
    agentServed: null,
    description:
      "Explore this 2 BHK apartment in Talegaon Dabhade to buy or invest in Pune city.",
  },
  {
    id: 8,
    title: "Kamakshie Suhas Sudhanva",
    location: "Rambaug Colony, Kothrud",
    area: "Pune",
    bhk: 2,
    carpetArea: 800,
    superArea: null,
    price: 13500000,
    pricePerSqft: 12857,
    floor: "6 out of 16",
    bathrooms: 2,
    balconies: 1,
    parking: "1 Covered",
    furnishing: "Unfurnished",
    facing: "East",
    overlooking: "Garden/Park",
    ownership: "Freehold",
    status: "Ready to Move",
    transaction: "Resale",
    amenities: ["Reserved Parking"],
    images: [images.img_10, images.img_11, images.img_12, images.img_13],
    postedTime: "Dec 27, '25",
    agentName: "Abhang Estates",
    agentType: "Agent",
    agentServed: "1500+",
    description:
      "East Facing Property. Come home to Kamakshie Rambaug Colony, Pune has an attractive 2 BHK apartment for sale.",
  },
  {
    id: 9,
    title: "Tain Square",
    location: "Fatima Nagar Wanowrie",
    area: "Pune",
    bhk: 3,
    carpetArea: null,
    superArea: 1650,
    price: 13500000,
    pricePerSqft: 8182,
    floor: "5 out of 11",
    bathrooms: 3,
    balconies: 2,
    parking: "2 Covered",
    furnishing: "Unfurnished",
    facing: "East",
    overlooking: "Main Road",
    ownership: "Co-operative Society",
    status: "Ready to Move",
    transaction: "Resale",
    amenities: [
      "Power Backup",
      "Reserved Parking",
      "Security",
      "Service/Goods Lift",
      "Visitor Parking",
    ],
    images: [images.img_11, images.img_12, images.img_13, images.img_14],
    postedTime: "Dec 27, '25",
    agentName: "N & G Enterprises",
    agentType: "Agent",
    agentServed: "100+",
    description:
      "East Facing Property. Near Inamdar hospital. A well-positioned 3 BHK flat in Fatima Nagar.",
  },
  {
    id: 10,
    title: "Shubh Shagun",
    location: "Kharadi",
    area: "Pune",
    bhk: 2,
    carpetArea: null,
    superArea: 839,
    price: 9000000,
    pricePerSqft: 10727,
    floor: "6 out of 14",
    bathrooms: 2,
    balconies: 2,
    parking: "1 Covered",
    furnishing: "Unfurnished",
    facing: "East",
    overlooking: "Pool, Garden/Park, Main Road",
    ownership: "Co-operative Society",
    status: "Ready to Move",
    transaction: "Resale",
    amenities: ["Reserved Parking", "Security"],
    images: [images.img_12, images.img_13, images.img_14, images.img_15],
    postedTime: "Dec 27, '25",
    agentName: "Property Dot Com",
    agentType: "Agent",
    agentServed: "4500+",
    description:
      "The 2 BHK apartment is immediately available for sale in Kharadi.",
  },
];

// Filter Options
export const bhkOptions = [
  { value: "all", label: "All BHK" },
  { value: "1", label: "1 BHK" },
  { value: "2", label: "2 BHK" },
  { value: "3", label: "3 BHK" },
  { value: "4", label: "4 BHK" },
  { value: "5", label: "5 BHK" },
];

export const budgetOptions = [
  { value: "all", label: "All Budgets" },
  { value: "0-4000000", label: "Under ₹40 Lac" },
  { value: "4000000-8000000", label: "₹40 - ₹80 Lac" },
  { value: "8000000-15000000", label: "₹80 L - ₹1.5 Cr" },
  { value: "15000000-25000000", label: "₹1.5 Cr - ₹2.5 Cr" },
  { value: "25000000-40000000", label: "₹2.5 Cr - ₹4 Cr" },
  { value: "40000000-999999999", label: "Above ₹4 Cr" },
];

export const furnishingOptions = [
  { value: "all", label: "All Types" },
  { value: "Furnished", label: "Furnished" },
  { value: "Semi-Furnished", label: "Semi-Furnished" },
  { value: "Unfurnished", label: "Unfurnished" },
];

export const localities = [
  "Kharadi",
  "Hinjewadi",
  "Viman Nagar",
  "Wagholi",
  "Magarpatta City",
  "Wakad",
  "Baner",
  "Kothrud",
  "Hadapsar",
  "Balewadi",
  "Kondhwa",
  "Punawale",
  "Pimpri Chinchwad",
  "Ghole Road",
  "Talegaon",
];

// Stats Data
export const statsData = {
  totalProperties: "30,625+",
  newProjects: "2,211+",
  verified: "100%",
  support: "24/7",
};
